### ISSUE TITLE
Update employee 

### ISSUE THREAD

**Issue by houspiller** [cubcoffee/valhalla-api#38]
create endpoint to update employee

**Comment by houspiller** [comment]
I think about not implementing UPDATE, it can be replaced by DELETE followed by a new INSERT

**Comment by houspiller** [comment]
@eduardomrodrigues @marcelorubim ???

**Comment by marcelorubim** [comment]
It's better to implement the update.

If the Employee is used as a foreign key in another table, it would be impossible to delete it.

And normally a REST API provides a method to update directly through one endpoint (PUT), instead of needing some logic to update (do delete then create).

**Comment by houspiller** [comment]
OK.... I'll do
